[
    { id: 1, apiname:"number0", question: "Hi, Let's get started. When's your Birthday?0",input: 'text' },
    { id: 2, apiname: "number1", question: "What's your first name?1", input: 'text' },
    { id: 3, apiname: "number2", question: "Almost done. What's your email?2", input: 'text' },
    { id: 4, apiname: "number3", question: "Now let's get you set up with a password.3", input: 'text' },
    { id: 5, apiname: "number4", question: "How did you hear about FamilyMatch?4", input: 'text' },
    { id: 6, apiname: "number5", question: "How would you describe your body type?5", input: 'text' },
    { id: 7, apiname: "number6", question: "Have you ever been married?6", input: 'text' },
    { id: 8, apiname: "number7", question: "Do you have kids?7", input: 'text' },
    { id: 9, apiname: "number8", question: 'Do you want kids?8', input: 'text' },
    { id: 10, apiname: "number9", question: "Which ethnicity best describe you?9", input: 'text' },
    { id: 11, apiname: "number10", question: "What interests you?10", input: 'text' },
    { id: 12, apiname: "number11", question: "Add a topic to your profile.11", input: 'text' },
    { id: 13, apiname: "number12", question: "Add a topic to your profile.12", input: 'text' },
    { id: 14, apiname: "number13", question: "Add a topic to your profile.13", input: 'file' },
    { id: 15, apiname: "number14", question: "Add a topic to your profile.14", input: 'text' },
    { id: 16, apiname: "number15", question: "Add a topic to your profile.15", input: 'text' },
    { id: 17, apiname: "number16", question: "Add a topic to your profile.16", input: 'text' },

]